version: "3.9"
services:
  stepup:
    environment:
      - TZ=Asia/Jakarta
    env_file:
      - .env
    image: $CI_REGISTRY_IMAGE:prod-latest
    container_name: stepup
    restart: unless-stopped
    expose:
      - "80"
    networks:
      liliumnet:
        ipv4_address: 192.168.1.8
    volumes:
      - stepup_data:/app/data
      - ./uploads:/app/uploads  # Mount the uploads directory

networks:
  liliumnet:
    external:
      name: liliumnet

volumes:
  stepup_data:  # Define the named volume